
include_guard()
include("${CMAKE_CURRENT_LIST_DIR}/linux-kitware-paraview.cmake")


set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
set(VTK_GROUP_ENABLE_Imaging "DONT_WANT" CACHE STRING "" FORCE)
set(VTK_GROUP_ENABLE_Parallel "DONT_WANT" CACHE STRING "" FORCE)
set(VTK_GROUP_ENABLE_Qt "DONT_WANT" CACHE STRING "" FORCE)
set(VTK_GROUP_ENABLE_StandAlone "DONT_WANT" CACHE STRING "" FORCE)
set(VTK_GROUP_ENABLE_Views "DONT_WANT" CACHE STRING "" FORCE)
set(VTK_GROUP_ENABLE_Web "DONT_WANT" CACHE STRING "" FORCE)
set(VTK_SMP_ENABLE_STDTHREAD OFF CACHE BOOL "" FORCE)
