
include_guard()
include("${CMAKE_CURRENT_LIST_DIR}/linux-kitware-paraview.cmake")

set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
set(PARAVIEW_PLUGINS_DEFAULT OFF CACHE BOOL "" FORCE)
set(PARAVIEW_USE_VISKORES OFF CACHE BOOL "" FORCE)
set(PARAVIEW_ENABLE_XDMF2 OFF CACHE BOOL "" FORCE)
set(PARAVIEW_USE_FORTRAN OFF CACHE BOOL "" FORCE)
set(PARAVIEW_USE_QTHELP OFF CACHE BOOL "" FORCE)
set(PARAVIEW_ENABLE_EMBEDDED_DOCUMENTATION OFF CACHE BOOL "" FORCE)
set(VTK_OPENGL_HAS_EGL OFF CACHE BOOL "" FORCE)
set(VTK_SMP_ENABLE_STDTHREAD OFF CACHE BOOL "" FORCE)